"""Default command templates for Tier 2 execution."""

from xfusion.capabilities.templates import CommandTemplate, TemplateParameter
from xfusion.policy.categories import PolicyCategory


def build_default_templates() -> list[CommandTemplate]:
    """Build default command templates for common operations."""
    return [
        # File operations
        CommandTemplate(
            name="file.read",
            description="Read contents of a file safely",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path to the file to read",
                ),
                TemplateParameter(
                    name="max_bytes",
                    type="integer",
                    required=False,
                    default=10000,
                    description="Maximum bytes to read",
                ),
            ],
            command="head -c {{max_bytes}} {{path}}",
            timeout=10,
            confirm_required=False,
            file_operations="read",
        ),
        CommandTemplate(
            name="file.list",
            description="List files in a directory",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="directory",
                    required=True,
                    description="Directory path to list",
                ),
                TemplateParameter(
                    name="limit",
                    type="integer",
                    required=False,
                    default=50,
                    description="Maximum number of entries to list",
                ),
            ],
            command="ls -la {{path}}",
            timeout=10,
            confirm_required=False,
            file_operations="read",
        ),
        CommandTemplate(
            name="file.create",
            description="Create a new file with content",
            category=PolicyCategory.WRITE_SAFE,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path where to create the file",
                ),
                TemplateParameter(
                    name="content",
                    type="string",
                    required=True,
                    description="Content to write to the file",
                ),
            ],
            command="echo {{content}} > {{path}}",
            timeout=10,
            confirm_required=True,
            file_operations="write",
            enabled=False,
        ),
        CommandTemplate(
            name="file.delete",
            description="Delete a file (requires confirmation)",
            category=PolicyCategory.DESTRUCTIVE,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path to the file to delete",
                ),
            ],
            command="rm {{path}}",
            timeout=10,
            confirm_required=True,
            file_operations="write",
        ),
        CommandTemplate(
            name="directory.create",
            description="Create a new directory",
            category=PolicyCategory.WRITE_SAFE,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path where to create the directory",
                ),
            ],
            command="mkdir -p {{path}}",
            timeout=10,
            confirm_required=True,
            file_operations="write",
        ),
        # Process operations
        CommandTemplate(
            name="process.list_all",
            description="List all running processes",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="limit",
                    type="integer",
                    required=False,
                    default=100,
                    description="Maximum number of processes to list",
                ),
            ],
            command="ps aux",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="process.find_by_name",
            description="Find processes by name pattern",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="pattern",
                    type="string",
                    required=True,
                    description="Pattern to search for in process names",
                ),
            ],
            command="pgrep -a {{pattern}}",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="process.terminate",
            description="Terminate a process by PID",
            category=PolicyCategory.DESTRUCTIVE,
            parameters=[
                TemplateParameter(
                    name="pid",
                    type="integer",
                    required=True,
                    description="Process ID to terminate",
                ),
                TemplateParameter(
                    name="signal",
                    type="string",
                    required=False,
                    default="TERM",
                    validation="^(TERM|KILL|INT|HUP)$",
                    description="Signal to send (TERM, KILL, INT, HUP)",
                ),
            ],
            command="kill -{{signal}} {{pid}}",
            timeout=10,
            confirm_required=True,
        ),
        # System information
        CommandTemplate(
            name="system.disk_usage",
            description="Check disk usage",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=False,
                    default="/",
                    description="Path to check disk usage for",
                ),
            ],
            command="df -h {{path}}",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.memory_usage",
            description="Check memory usage",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="free -h",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.uptime",
            description="Check system uptime",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="uptime",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.kernel_info",
            description="Check kernel and system info",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="uname -a",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.cpu_usage",
            description="Get current CPU usage snapshot",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="top -bn1",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.memory_pressure",
            description="Check memory pressure and swap",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="vmstat -s",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.iostat",
            description="Check disk I/O statistics",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="iostat -xz 1 1",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.ulimits",
            description="Check system resource limits (ulimit)",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="ulimit -a",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.routing_table",
            description="Check network routing table",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="ip route",
            timeout=10,
            confirm_required=False,
        ),
        # Resource Analysis
        CommandTemplate(
            name="system.cpu_steal",
            description="Check CPU steal time (virtualization overhead)",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="mpstat 1 1",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.swap_usage",
            description="Detailed swap usage analysis",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="swapon --show",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.oom_events",
            description="Detect recent OOM killer events",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="dmesg",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.disk_io_wait",
            description="Check disk I/O wait statistics",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="iostat -c",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.load_avg",
            description="Check system load average",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="uptime",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.disk_info",
            description="List block devices and topology",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="lsblk",
            timeout=10,
            confirm_required=False,
        ),
        # Storage Management
        CommandTemplate(
            name="system.mount_info",
            description="Show current mount points",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="mount",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.mount",
            description="Mount a filesystem",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="device",
                    type="string",
                    required=True,
                    description="Device node or partition",
                ),
                TemplateParameter(
                    name="path",
                    type="directory",
                    required=True,
                    description="Mount point",
                ),
            ],
            command="sudo mount {{device}} {{path}}",
            timeout=30,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.unmount",
            description="Unmount a filesystem",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Mount point or device",
                ),
            ],
            command="sudo umount {{path}}",
            timeout=30,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.inode_usage",
            description="Check inode usage per filesystem",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="df -i",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.firewall_status",
            description="Check firewall status (iptables)",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="sudo iptables -L -n",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.list_packages",
            description="List installed packages (dpkg)",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="dpkg -l",
            timeout=30,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.last_logins",
            description="Show last logged in users",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="limit",
                    type="integer",
                    required=False,
                    default=20,
                    description="Number of entries to show",
                ),
            ],
            command="last -n {{limit}}",
            timeout=10,
            confirm_required=False,
        ),
        # Network (read-only)
        CommandTemplate(
            name="network.connections",
            description="List network connections",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="port",
                    type="integer",
                    required=False,
                    description="Filter by port number",
                ),
            ],
            command="ss -tlnp",
            timeout=10,
            confirm_required=False,
            network_restricted=True,
        ),
        CommandTemplate(
            name="network.interfaces",
            description="List network interfaces",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="ip addr show",
            timeout=10,
            confirm_required=False,
            network_restricted=True,
        ),
        CommandTemplate(
            name="network.ping",
            description="Check connectivity to a host",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="host",
                    type="string",
                    required=True,
                    description="Hostname or IP address to ping",
                ),
                TemplateParameter(
                    name="count",
                    type="integer",
                    required=False,
                    default=4,
                    description="Number of packets to send",
                ),
            ],
            command="ping -c {{count}} {{host}}",
            timeout=15,
            confirm_required=False,
            network_restricted=True,
        ),
        CommandTemplate(
            name="network.dns_lookup",
            description="Resolve a hostname to IP addresses",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="hostname",
                    type="string",
                    required=True,
                    description="Hostname to resolve",
                ),
            ],
            command="host {{hostname}}",
            timeout=10,
            confirm_required=False,
            network_restricted=True,
        ),
        CommandTemplate(
            name="network.traceroute",
            description="Trace the network path to a host",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="host",
                    type="string",
                    required=True,
                    description="Hostname or IP address to trace",
                ),
            ],
            command="traceroute -m 20 {{host}}",
            timeout=30,
            confirm_required=False,
            network_restricted=True,
        ),
        CommandTemplate(
            name="network.port_check",
            description="Check if a port is open on a host",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="host",
                    type="string",
                    required=True,
                    description="Hostname or IP address",
                ),
                TemplateParameter(
                    name="port",
                    type="integer",
                    required=True,
                    description="Port number",
                ),
            ],
            command="nc -zv -w 5 {{host}} {{port}}",
            timeout=10,
            confirm_required=False,
            network_restricted=True,
        ),
        # Network Control
        CommandTemplate(
            name="network.block_ip",
            description="Block an IP address via iptables",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="ip",
                    type="string",
                    required=True,
                    description="IP address to block",
                ),
            ],
            command="sudo iptables -A INPUT -s {{ip}} -j DROP",
            timeout=10,
            confirm_required=True,
        ),
        CommandTemplate(
            name="network.unblock_ip",
            description="Unblock an IP address via iptables",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="ip",
                    type="string",
                    required=True,
                    description="IP address to unblock",
                ),
            ],
            command="sudo iptables -D INPUT -s {{ip}} -j DROP",
            timeout=10,
            confirm_required=True,
        ),
        # Cleanup operations
        CommandTemplate(
            name="cleanup.temp_files",
            description="List temporary files older than N days",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="directory",
                    required=True,
                    description="Directory to search in",
                ),
                TemplateParameter(
                    name="days",
                    type="integer",
                    required=False,
                    default=7,
                    description="Files older than this many days",
                ),
            ],
            command="find {{path}} -type f -mtime +{{days}} -ls",
            timeout=30,
            confirm_required=False,
            file_operations="read",
        ),
        CommandTemplate(
            name="cleanup.delete_temp_files",
            description="Delete temporary files older than N days",
            category=PolicyCategory.DESTRUCTIVE,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="directory",
                    required=True,
                    description="Directory to clean",
                ),
                TemplateParameter(
                    name="days",
                    type="integer",
                    required=False,
                    default=7,
                    description="Files older than this many days",
                ),
            ],
            command="find {{path}} -type f -mtime +{{days}} -delete",
            timeout=30,
            confirm_required=True,
            file_operations="write",
        ),
        # Log operations
        CommandTemplate(
            name="logs.tail",
            description="View last lines of a log file",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path to the log file",
                ),
                TemplateParameter(
                    name="lines",
                    type="integer",
                    required=False,
                    default=50,
                    description="Number of lines to show",
                ),
            ],
            command="tail -n {{lines}} {{path}}",
            timeout=10,
            confirm_required=False,
            file_operations="read",
        ),
        CommandTemplate(
            name="logs.search",
            description="Search for pattern in log file",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path to the log file",
                ),
                TemplateParameter(
                    name="pattern",
                    type="string",
                    required=True,
                    description="Pattern to search for",
                ),
            ],
            command="grep {{pattern}} {{path}}",
            timeout=30,
            confirm_required=False,
            file_operations="read",
        ),
        CommandTemplate(
            name="logs.journalctl",
            description="View systemd journal logs",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="lines",
                    type="integer",
                    required=False,
                    default=50,
                    description="Number of lines to show",
                ),
            ],
            command="journalctl -n {{lines}}",
            timeout=30,
            confirm_required=False,
        ),
        CommandTemplate(
            name="logs.read_segment",
            description="Read a specific segment of a log file",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path to the log file",
                ),
                TemplateParameter(
                    name="start_line",
                    type="integer",
                    required=True,
                    description="First line to read",
                ),
                TemplateParameter(
                    name="end_line",
                    type="integer",
                    required=True,
                    description="Last line to read",
                ),
            ],
            command="sed -n {{start_line}},{{end_line}}p {{path}}",
            timeout=10,
            confirm_required=False,
            file_operations="read",
        ),
        # Security Monitoring
        CommandTemplate(
            name="logs.failed_logins",
            description="Check failed login attempts",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="lastb",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.active_sessions",
            description="List active user sessions",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="who",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="security.suid_scan",
            description="Scan for SUID files (potential privilege escalation points)",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="directory",
                    required=False,
                    default="/usr/bin",
                    description="Directory to scan",
                ),
            ],
            command="find {{path}} -perm -4000 -ls",
            timeout=30,
            confirm_required=False,
        ),
        CommandTemplate(
            name="logs.filter_time",
            description="Filter journal logs by time",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="since",
                    type="string",
                    required=True,
                    description="Start time (e.g., '1 hour ago', '2026-04-25 00:00:00')",
                ),
            ],
            command="journalctl --since {{since}}",
            timeout=30,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.package_action",
            description="Install, remove, or update a package",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="package",
                    type="string",
                    required=True,
                    description="Package name",
                ),
                TemplateParameter(
                    name="action",
                    type="string",
                    required=True,
                    validation="^(install|remove|purge|update)$",
                    description="Action to perform (install, remove, purge, update)",
                ),
            ],
            command="sudo apt-get -y {{action}} {{package}}",
            timeout=300,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.upgrade",
            description="Upgrade all system packages",
            category=PolicyCategory.PRIVILEGED,
            parameters=[],
            command="sudo apt-get -y upgrade",
            timeout=1200,
            confirm_required=True,
        ),
        # Maintenance
        CommandTemplate(
            name="system.prune_packages",
            description="Remove unused packages",
            category=PolicyCategory.PRIVILEGED,
            parameters=[],
            command="sudo apt-get -y autoremove",
            timeout=300,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.clear_cache",
            description="Sync and clear page cache (privileged)",
            category=PolicyCategory.PRIVILEGED,
            parameters=[],
            command="sudo sync",
            timeout=10,
            confirm_required=True,
        ),
        # User Management
        CommandTemplate(
            name="user.list",
            description="List system users",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="cat /etc/passwd",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="user.add_to_group",
            description="Add a user to a group",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="username",
                    type="string",
                    required=True,
                    description="Username",
                ),
                TemplateParameter(
                    name="group",
                    type="string",
                    required=True,
                    description="Group name",
                ),
            ],
            command="sudo usermod -aG {{group}} {{username}}",
            timeout=10,
            confirm_required=True,
        ),
        CommandTemplate(
            name="user.remove_from_group",
            description="Remove a user from a group",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="username",
                    type="string",
                    required=True,
                    description="Username",
                ),
                TemplateParameter(
                    name="group",
                    type="string",
                    required=True,
                    description="Group name",
                ),
            ],
            command="sudo gpasswd -d {{username}} {{group}}",
            timeout=10,
            confirm_required=True,
        ),
        CommandTemplate(
            name="user.check_permissions",
            description="Check effective permissions for a user",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="username",
                    type="string",
                    required=True,
                    description="Username",
                ),
            ],
            command="id {{username}}",
            timeout=10,
            confirm_required=False,
        ),
        # Job Management
        CommandTemplate(
            name="user.cron_list",
            description="List crontab for current user",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="crontab -l",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="user.at_list",
            description="List scheduled 'at' jobs",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="atq",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="user.at_cancel",
            description="Cancel a scheduled 'at' job",
            category=PolicyCategory.WRITE_SAFE,
            parameters=[
                TemplateParameter(
                    name="job_id",
                    type="integer",
                    required=True,
                    description="Job ID to cancel",
                ),
            ],
            command="atrm {{job_id}}",
            timeout=10,
            confirm_required=True,
        ),
        # Advanced Process Inspection
        CommandTemplate(
            name="process.pstree",
            description="Show process hierarchy as a tree",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="pid",
                    type="integer",
                    required=False,
                    description="Root PID of the tree",
                ),
            ],
            command="pstree -p {{pid}}",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="process.threads",
            description="List threads for a process",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="pid",
                    type="integer",
                    required=True,
                    description="Process PID",
                ),
            ],
            command="ps -T -p {{pid}}",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="process.lsof",
            description="List open files for a process",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="pid",
                    type="integer",
                    required=True,
                    description="Process PID",
                ),
            ],
            command="lsof -p {{pid}}",
            timeout=10,
            confirm_required=False,
        ),
        # Container Management
        CommandTemplate(
            name="container.list",
            description="List all containers",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="docker ps -a",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="container.inspect",
            description="Inspect container details",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="container_id",
                    type="string",
                    required=True,
                    description="Container ID or name",
                ),
            ],
            command="docker inspect {{container_id}}",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="container.start",
            description="Start a stopped container",
            category=PolicyCategory.WRITE_SAFE,
            parameters=[
                TemplateParameter(
                    name="container_id",
                    type="string",
                    required=True,
                    description="Container ID or name",
                ),
            ],
            command="docker start {{container_id}}",
            timeout=30,
            confirm_required=True,
        ),
        CommandTemplate(
            name="container.stop",
            description="Stop a running container",
            category=PolicyCategory.DESTRUCTIVE,
            parameters=[
                TemplateParameter(
                    name="container_id",
                    type="string",
                    required=True,
                    description="Container ID or name",
                ),
            ],
            command="docker stop {{container_id}}",
            timeout=30,
            confirm_required=True,
        ),
        CommandTemplate(
            name="container.restart",
            description="Restart a container",
            category=PolicyCategory.DESTRUCTIVE,
            parameters=[
                TemplateParameter(
                    name="container_id",
                    type="string",
                    required=True,
                    description="Container ID or name",
                ),
            ],
            command="docker restart {{container_id}}",
            timeout=60,
            confirm_required=True,
        ),
        CommandTemplate(
            name="container.logs",
            description="View container logs",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="container_id",
                    type="string",
                    required=True,
                    description="Container ID or name",
                ),
                TemplateParameter(
                    name="lines",
                    type="integer",
                    required=False,
                    default=50,
                    description="Number of lines to show",
                ),
            ],
            command="docker logs --tail {{lines}} {{container_id}}",
            timeout=20,
            confirm_required=False,
        ),
        # Kernel & Sysctl
        CommandTemplate(
            name="system.sysctl_read",
            description="Read kernel parameters (sysctl)",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="variable",
                    type="string",
                    required=False,
                    description="Kernel variable name (e.g., net.ipv4.ip_forward)",
                ),
            ],
            command="sysctl {{variable}}",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.sysctl_write",
            description="Update kernel parameter (sysctl)",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="variable",
                    type="string",
                    required=True,
                    description="Kernel variable name",
                ),
                TemplateParameter(
                    name="value",
                    type="string",
                    required=True,
                    description="New value",
                ),
            ],
            command="sudo sysctl -w {{variable}}={{value}}",
            timeout=10,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.lsmod",
            description="List loaded kernel modules",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="lsmod",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.modprobe_load",
            description="Load a kernel module",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="module",
                    type="string",
                    required=True,
                    description="Module name",
                ),
            ],
            command="sudo modprobe {{module}}",
            timeout=30,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.modprobe_remove",
            description="Unload a kernel module",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="module",
                    type="string",
                    required=True,
                    description="Module name",
                ),
            ],
            command="sudo modprobe -r {{module}}",
            timeout=30,
            confirm_required=True,
        ),
        CommandTemplate(
            name="logs.dmesg",
            description="Show kernel ring buffer messages",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="dmesg",
            timeout=10,
            confirm_required=False,
        ),
        # App Debugging
        CommandTemplate(
            name="system.env_read",
            description="Read environment variables for current session",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="env",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="process.env_dump",
            description="Dump environment variables for a specific PID",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="pid",
                    type="integer",
                    required=True,
                    description="Process PID",
                ),
            ],
            command="sudo cat /proc/{{pid}}/environ",
            timeout=10,
            confirm_required=False,
        ),
        # System Validation
        CommandTemplate(
            name="file.checksum",
            description="Calculate SHA256 checksum of a file",
            category=PolicyCategory.READ_ONLY,
            parameters=[
                TemplateParameter(
                    name="path",
                    type="string",
                    required=True,
                    description="Path to the file",
                ),
            ],
            command="sha256sum {{path}}",
            timeout=30,
            confirm_required=False,
            file_operations="read",
        ),
        # Runtime Control
        CommandTemplate(
            name="process.set_priority",
            description="Change scheduling priority of a process (renice)",
            category=PolicyCategory.PRIVILEGED,
            parameters=[
                TemplateParameter(
                    name="pid",
                    type="integer",
                    required=True,
                    description="Process PID",
                ),
                TemplateParameter(
                    name="priority",
                    type="integer",
                    required=True,
                    description="New priority (-20 to 19)",
                ),
            ],
            command="sudo renice -n {{priority}} -p {{pid}}",
            timeout=10,
            confirm_required=True,
        ),
        # Backup & Recovery
        CommandTemplate(
            name="system.backup_create",
            description="Create a compressed backup archive",
            category=PolicyCategory.WRITE_SAFE,
            parameters=[
                TemplateParameter(
                    name="source",
                    type="string",
                    required=True,
                    description="Path to back up",
                ),
                TemplateParameter(
                    name="destination",
                    type="string",
                    required=True,
                    description="Archive path (e.g., /tmp/backup.tar.gz)",
                ),
            ],
            command="tar -czf {{destination}} {{source}}",
            timeout=300,
            confirm_required=True,
        ),
        CommandTemplate(
            name="system.backup_restore",
            description="Restore a backup archive",
            category=PolicyCategory.DESTRUCTIVE,
            parameters=[
                TemplateParameter(
                    name="archive",
                    type="string",
                    required=True,
                    description="Path to archive",
                ),
                TemplateParameter(
                    name="destination",
                    type="directory",
                    required=True,
                    description="Restore destination",
                ),
            ],
            command="tar -xzf {{archive}} -C {{destination}}",
            timeout=300,
            confirm_required=True,
        ),
        # Metrics
        CommandTemplate(
            name="system.metrics_snapshot",
            description="Collect a snapshot of system metrics",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="sar -u 1 1",
            timeout=10,
            confirm_required=False,
        ),
        CommandTemplate(
            name="system.resource_summary",
            description="Summarize top resource consuming processes",
            category=PolicyCategory.READ_ONLY,
            parameters=[],
            command="ps -eo pcpu,pmem,user,args --sort=-pcpu",
            timeout=10,
            confirm_required=False,
        ),
    ]
